### ISSUE TITLE
Units Update

### ISSUE THREAD

**Issue by zacadelman** [USEPA/AMET#43]
The update mode for the AQ database scripts doesn't appear to work as expected.  Once a project has been created, the units table does not get updated correctly.  It actually looks like it's being clobbered (networks deleted) when you try to update the table.  

When I grep on the log from the aqProject.csh script, run in update mode, I see this message (check to see which networks are being loaded into the db: 

```
Finshed populating database for network  IMPROVE 
Finshed populating database for network  CSN 
Finshed populating database for network  CASTNET 
Finshed populating database for network  CASTNET_Hourly 
Finshed populating database for network  CASTNET_Daily 
Finshed populating database for network  CASTNET_Drydep 
Finshed populating database for network  NADP 
Finshed populating database for network  MDN 
Finshed populating database for network  AMON 
```

When I query the database, I'm only seeing that the last network processed exists in the units table:

```
mysql> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| amet_example       |
| amet_iwdw          |
| mysql              |
| performance_schema |
+--------------------+
5 rows in set (0.00 sec)

mysql> use amet_iwdw  ;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables;
+----------------------+
| Tables_in_amet_iwdw  |
+----------------------+
| WAQS_Base11b         |
| WAQS_Base11b_CAMx12k |
| WAQS_Base11b_CAMx4k  |
| aq_project_log       |
| project_units        |
| site_metadata        |
+----------------------+
6 rows in set (0.00 sec)

mysql> select network from project_units;
+---------+
| network |
+---------+
| AMON    |
+---------+
1 row in set (0.00 sec)
```

This is a problem because the units are used in the plotting scripts for various conditionals.  If the units are NULL in the database, the plotting scripts don't work.

**Comment by zacadelman** [comment]
Update on this issue.  This actually doesn't seem to be just an issue with updated databases, I also see it when I load a new project from scratch. I'm trying to apply AMET for a new AQ project.  

When I load the project using scripts_db/aqProject.csh, the project_units table is only storing the last network loaded.  So if I try to load IMPROVE, CSN, and AQS, in that order, at the end of the process only AQS shows up in the project_units table. If I watch the database while the project load script is running, I will actually see the networks load and then disappear as each one cycles through in the processing.

**Comment by wkappel** [comment]
I have quick fix for this issue I believe. This is a directly result of me not quite understanding the intricacies of MySQL database programming. While I setup the units table to have two unique index columns, it seems the way I setup those up has an effect on how they function. I'm going back to my original way of setting them up, which should work correctly.

**Comment by wkappel** [comment]
I pushed the update to the AQ_setup_dbase.R script to the release repo. Zac, if you want to correct your existing database project_units table, you can simply run the commands:

alter table project_units drop index proj_code;
alter table project_units drop index network;
alter table project_units add UNIQUE(proj_code,network);

**Comment by zacadelman** [comment]
There is someone peculiar with the way that the project_units table is being initialized.  I think the problem is on line 61 of AQ_setup_dbase.R:

```
aq_new_1 <- "create table project_units (proj_code varchar(100) UNIQUE KEY, network varchar(25) UNIQUE KEY)"
```

From what I can tell, making the proj_code a unique key, coupled with the `REPLACE INTO` statement on line 155 of AQ_add2dbase.R is causing the entries in proj_code to be overwritten when new networks are added.  This is from the mysql manual:

"REPLACE works exactly like INSERT, except that if an old row in the table has the same value as a new row for a PRIMARY KEY or a UNIQUE index, the old row is deleted before the new row is inserted."

I'm not the best with mysql so figuring out the solution to this should probably come from you, Wyat.

**Comment by zacadelman** [comment]
I added that last comment before I saw your fixes.  It looks like we found the same issue.  I'll take a look at your code fix.  Thanks!

**Comment by zacadelman** [comment]
There is still an issue with the fix that you uploaded.  The networks within a project update as expected.  There is problem when you try to add another project within the same database. As the networks get added to the new project, they get deleted from the previous project.  

So I have two projects, one for a 12km run and the second for a 4km nest.  They should be able to be loaded into the same database. I loaded the 12km data using the fixed code you provided. I then ran the script to load the 4km data; as each network loaded into the project_units table for the new 4km project, the network disappeared from the 12km project in the table.

**Comment by wkappel** [comment]
Couple questions.

Did you create a new database, or work from an existing one?
If you are working off an existing one, did you fix the project_units table as I suggested above?
If you started with a new database, can you run a describe on the project_units table and tell me what the key is after proj_code and network?

**Comment by wkappel** [comment]
Just tested this on my end and it seems to work. I just want to make sure you fixed the database before testing. I'm sure you did, but just in case. 

Otherwise, the issue could potentially be with the versions of MySQL, although that seems unlikely.

**Comment by zacadelman** [comment]
You were right.  I didn't delete my old database first.  Once I did this, your fix works fine.  Sorry for the confusion.

**Comment by wkappel** [comment]
No problem. Thanks for identifying and reporting this issue as well. I'll need to dig deeper in the MySQL programming to see if there is another solution, but this works for now. Closing this issue.
